### ISSUE TITLE
bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by damiendube** [stefankoegl/python-json-pointer#19]
After installing from pip
$ sudo pip install jsonpointer

Running jsonpointer gives me this error.
-bash: /usr/local/bin/jsonpointer: /home/stefan/work/python-json-patch/venv/bin/python: bad interpreter: No such file or directory

**Comment by stefankoegl** [comment]
I've just released jsonpointer 1.10 which should fix this issue. Can you verify?

Thanks!
