### ISSUE TITLE
Provide an API for detecting invalid JSON Pointers

### ISSUE THREAD

**Issue by Julian** [stefankoegl/python-json-pointer#20]
Hi!

Would you consider an API to validate whether a particular input was valid under RFC 6901 (or does such a thing exist already and I've missed it)?

E.g., `/foo/bar~` is not a valid JSON Pointer seemingly (the ~ is not escaped), but I cannot see an API that complains about that -- jsonpointer.JsonPointer will happily accept it as another pointer part.

(Even having jsonpointer.JsonPointer do enough validation of its inputs would also work).

Full context: JSON Schema Draft 6 adds a [jsonpointer format](http://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3.9). I'd love to use python-json-pointer to implement it in [jsonschema](https://github.com/Julian/jsonschema).

**Comment by stefankoegl** [comment]
JsonPointer is already doing some form of input validation (eg it complains if there is no leading `/`). I've now extended this for the cases you mentioned in #24.

Can you please have a look if this would meet your requirements?

**Comment by Julian** [comment]
Hey! Thanks, that does work, and passes all the tests. Appreciated!

**Comment by stefankoegl** [comment]
I've just released version 1.14 with the new validations.

**Comment by Julian** [comment]
Awesome! Will have a look, thanks so much!

**Comment by Julian** [comment]
Just confirming, looks spot on, thanks again.
