### ISSUE TITLE
Curious about modified BSD license?

### ISSUE THREAD

**Issue by ivoanjo** [stefankoegl/python-json-pointer#35]
Hello there, and thanks for the awesome library!

While taking a look at the source today I noticed that it was listed as having a "modified BSD" license. I was curious to see what was modified and if I should be aware when using it, so I generated a quick diff between the usual [BSD license](https://opensource.org/licenses/BSD-3-Clause) and the one for the project:

```diff
-Copyright <YEAR> <COPYRIGHT HOLDER>
+Copyright (c) 2011 Stefan Kögl <stefan@skoegl.net>
+All rights reserved.
 
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
@@ -9,13 +10,13 @@
 2. Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
-3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products
+3. The name of the author may not be used to endorse or promote products
    derived from this software without specific prior written permission.
 
-THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR
+THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
-IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
+IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
```

The change seems rather harmless as far as use goes; for contribution I wonder if changing "the copyright holders and contributors" to "the author" would mean that other contributors would not be exempted in some of the clauses...?

My question is: I'm curious what the motivation behind the modified license is, and have you considered going back to the usual wording?

Thanks :pray:

**Comment by stefankoegl** [comment]
The link that you included mentions

> Note: This license has also been called the "New BSD License" or "Modified BSD License".

It is essentially just another name for the 3-clause BSD license. Does this answer your questions?

**Comment by ivoanjo** [comment]
Thanks @stefankoegl -- so does that mean that this project's license is intended to be the same as the 3-clause BSD license I linked to above?

**Comment by stefankoegl** [comment]
Yes, that's right.

**Comment by ivoanjo** [comment]
Ah, great then! The fact that GitHub cannot identify the license and on PyPI it says it is "modified" threw me off.

It might be worth just replacing with the OSI wording, as that ensures the tools pick it up (I don't mind submitting the PR), but from my side, thank you very much for clearing it up, and feel free to close the ticket! 🙏

Have a great weekend!

**Comment by stefankoegl** [comment]
As I pointed out before, "Modified BSD License" is a correct name for the license. This is also mentioned in the link you provided in your original description. GitHub correctly determined the license.

**Comment by ivoanjo** [comment]
> As I pointed out before, "Modified BSD License" is a correct name for the license. 

Of course, you are correct. What I meant was the wording on the license file itself (which is almost, but not quite the common wording shared in the OSI website) not the license name.
