### ISSUE TITLE
Missing GIT Tag for v3.0.0

### ISSUE THREAD

**Issue by hswong3i** [stefankoegl/python-json-pointer#61]
I found that https://pypi.org/project/jsonpointer/3.0.0/ get released with PyPi, but couldn't find the corresponding GIT tag https://github.com/stefankoegl/python-json-pointer/releases/tag/v3.0.0.

Are we missing it?

**Comment by stefankoegl** [comment]
Thanks for letting me know - I pushed the missing tag: https://github.com/stefankoegl/python-json-pointer/tree/v3.0.0
