### ISSUE TITLE
resolve_pointer() won't always return the default.

### ISSUE THREAD

**Issue by thekafkaf** [stefankoegl/python-json-pointer#9]
I noticed the behavior in to cases:
1. The path that was given was longer the the dicts depth and the last object resolved was a string.
2. The 'doc' obj to be resolved against was not a dict nor a list and the path was'nt defined.

Both this cases are the product of the handling of getitem in the function walk(), in case the doc is not a list nor a dict, getitem is called without an except. 
Is there a reason for that? If not, I'd would be more than happy to open a pull request with new tests and a fix.

**Comment by stefankoegl** [comment]
While reviewing open issues, I noticed that this is already fixed in the latest version.

```` python
>>> from jsonpointer import resolve_pointer
>>> from collections.abc import MutableMapping
>>> 
>>> class Foo(MutableMapping):
...     def __init__(self, d):
...         self.d = d
...     def __getitem__(self, item):
...         return self.d[item]
...     def __len__(self):
...         return len(self.d)
...     def __iter__(self):
...         return iter(self.d)
...     def __delitem__(self, item):
...         del self.d[item]
...     def __setitem__(self, key, value):
...         self.d[key] = value
... 
>>> f = Foo({'a': {'b': 'c'}})
>>> resolve_pointer(f, '/x/y', None) is None
True
>>> resolve_pointer(f, '/x/y', 'x') == 'x'
True
>>> 
>>> d = {'a': {'b': 'c'}}
>>> resolve_pointer(d, '/a/b/d', 'y') == 'y'
True
````
